timezone: "America/Sao_Paulo"
lookback_hours: 30
queries:
  - 'debêntures OR "debenture incentivada" OR "lei 12.431"'
  - 'CRA OR "certificado de recebíveis do agronegócio"'
  - 'CRI OR "certificado de recebíveis imobiliários"'
  - 'FIDC OR securitização OR "direitos creditórios"'
  - '"mercado de capitais" OR DCM OR "oferta pública"'
  - '"letra financeira" OR LF'
  - '"CVM 175" OR "ICVM 160" OR "ICVM 158"'
  - 'ANBIMA debêntures'
sources_preferidas:
  - "valor.globo.com"
  - "exame.com"
  - "braziljournal.com"
  - "neofeed.com.br"
  - "pipelinevalor.globo.com"
  - "infomoney.com.br"
  - "oglobo.globo.com"
  - "folha.uol.com.br"
  - "estadao.com.br"
  - "globorural.globo.com"
  - "agribiz.com.br"
  - "canalrural.com.br"
  - "agrolink.com.br"
  - "noticiasagricolas.com.br"
  - "reuters.com"
  - "bloomberg.com"
  - "moneytimes.com.br"
  - "investnews.com.br"
  - "capitalaberto.com.br"
  - "istoedinheiro.com.br"
  - "epocanegocios.globo.com"
  - "canalenergia.com.br"
  - "dci.com.br"
  - "jornaldocomercio.com"
  - "portalenergia.com.br"
  - "energiahoje.com"
  - "petronoticias.com.br"
  - "aneel.gov.br"
  - "ons.org.br"
  - "portalsaneamento.com.br"
  - "revistainfra.com.br"
  - "infraestrutura.gov.br"
  - "antf.org.br"
  - "cnt.org.br"
  - "abcr.org.br"
  - "portogente.com.br"
  - "mundologistica.com.br"
  - "ferroviario.com.br"
  - "aeroportosbrasil.com.br"
  - "infrasa.com.br"
  - "mobilize.org.br"
  - "cbic.org.br"
  - "sindusconsp.com.br"
email:
  enabled: true
  provider: "outlook"  # gmail, outlook, hotmail
  from: "andrewlopes_oliveira@hotmail.com"
  to: ["alopes@bcpsecurities.com"]
  subject_prefix: "[Clipping Crédito]"
telegram:
  enabled: false
  bot_token: ""
  chat_id: ""
output_dir: "output"
